In [ ]:
#np.array
import numpy as np

a=np.array([1,2,3])
print(a)
b= np.array([[1,2,3], [4,5,6]])
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
#3d array
c= np.array ([[[1,2,3],[4,5,6]],[[6,7,8],[9,0,1]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [9 0 1]]]


In [ ]:
# d type
np.array([1,2,3], dtype= bool)
np.array([1,2,3], dtype= float)
np.array([1,2,3], dtype= complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#np.arange
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#np.reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#ones and zeros
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((1,2))


array([[0.4563858 , 0.42405376]])

In [ ]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY ATTRIBUTES


In [ ]:
a1= np.arange(10)
a2= np.arange(12,dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
#ndim
a1.ndim
a2.ndim
a3.ndim

3

In [ ]:
#shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [ ]:
#size
a1.size
a2.size
a3.size

8

In [ ]:
#itemsize
a1.itemsize
a2.itemsize
a3.itemsize

8

In [ ]:
#dtype
a1.dtype
a2.dtype
a3.dtype

dtype('int64')

Changing Datatype

In [ ]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
#Scalar Operations
#arithmetic
a1*2
a2*3

array([[36, 39, 42, 45],
       [48, 51, 54, 57],
       [60, 63, 66, 69]])

In [ ]:
#relational
a2>5
a1<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
#Vector Operations
a1+a2
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

**Array Functions**

In [ ]:
a1 = np.random.random((3,3))
a2 = np.round(a1*100)
a1


array([[0.32475618, 0.59162158, 0.50544053],
       [0.95670912, 0.41528617, 0.45545231],
       [0.90135294, 0.10019136, 0.67102666]])

In [ ]:
#max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))
print(np.max(a1,axis=1))

0.8907447859722604
0.2979881552291137
5.673474595816557
0.009875583680371326
[0.69904429 0.85050209 0.89074479]


In [ ]:
#mean/median/std/var

print(np.mean(a1))
print(np.mean(a1,axis=1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

0.5468707600289141
[0.47393943 0.6091492  0.55752365]
0.5054405334344068
0.2554490830370533
0.06525423402447138


In [ ]:
#Trigonometric functions
np.sin(a1)

array([[0.31907772, 0.55770773, 0.48419294],
       [0.81729975, 0.40345179, 0.43986856],
       [0.7841672 , 0.10002381, 0.62179038]])

In [ ]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(np.dot(a2,a3))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [ ]:
#logs and exponential
print(np.log(a1))
print(np.exp(a1))

[[-1.12468061 -0.52488807 -0.68232489]
 [-0.04425588 -0.87878744 -0.78646428]
 [-0.10385837 -2.30067337 -0.39894642]]
[[1.38369323 1.8069161  1.65771564]
 [2.60311582 1.51480416 1.57688646]
 [2.46293307 1.10538242 1.95624468]]


In [ ]:
#round/floor/ceil
print(np.round(np.random.random((2,3))*100))
print(np.round(np.random.random((2,3))*100))
print(np.round(np.random.random((2,3))*100))

[[62. 43. 97.]
 [80. 83. 65.]]
[[68. 70. 37.]
 [78. 14. 50.]]
[[ 3. 38. 15.]
 [87. 74. 40.]]


**Indexing And Slicing**

In [5]:
import numpy as np
a1= np.arange(10)
a2= np.arange(12).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(a1[-1])
print(a1[0])

print(a2[1,2])
print(a2[2,3])
print(a2[1,0])

print(a3[1,0,1])
print(a3[0,1,0])
print(a3[0,0,0])


9
0
6
11
4
5
2
0


In [ ]:
#1d matrix slicing

print(a1[2:5])

#2d matrix slicing

print(a2[0,:])
print(a2[:,2])
print(a2[1:,1:3])
print(a2[::2,::3])
print(a2[0:2,1:])

#3d matrix slicing
a3= np.arange(27).reshape(3,3,3)

print(a3[1])
print(a3[0,1,:])
print(a3[1,:,1])
print(a3[2,1:,1:])
print(a3[::2,0,::2])



[2 3 4]
[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[1 2 3]
 [5 6 7]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


**Iterating**

In [ ]:
for i in a1:
  print(i)

for i in a2:
  print(i)

for i in a3:
  print(i)

for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**Reshaping**

In [ ]:
#reshape

In [7]:
#transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [8]:
#ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**Stacking**

In [12]:
#hprizontal stacking
a4= np.arange(12).reshape(3,4)
a5= np.arange(12,24).reshape(3,4)

print(np.hstack((a4,a5)))
print(np.hstack((a4,a5,a4,a5)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3 12 13 14 15  0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19  4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23  8  9 10 11 20 21 22 23]]


In [14]:
#vertical stacking
print(np.vstack((a4,a5)))
print(np.vstack((a4,a5,a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


**Splitting**

In [15]:
#horizontal spliting

np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [16]:
#vertical spliting

np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]