In [ ]:
#np.array
import numpy as np

a=np.array([1,2,3])
print(a)
b= np.array([[1,2,3], [4,5,6]])
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
#3d array
c= np.array ([[[1,2,3],[4,5,6]],[[6,7,8],[9,0,1]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [9 0 1]]]


In [ ]:
# d type
np.array([1,2,3], dtype= bool)
np.array([1,2,3], dtype= float)
np.array([1,2,3], dtype= complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#np.arange
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#np.reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#ones and zeros
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((1,2))


array([[0.12209373, 0.52420414]])

In [ ]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY ATTRIBUTES


In [ ]:
a1= np.arange(10)
a2= np.arange(12,dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#ndim
a1.ndim
a2.ndim
a3.ndim

2

In [ ]:
#shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [ ]:
#size
a1.size
a2.size
a3.size

8

In [ ]:
#itemsize
a1.itemsize
a2.itemsize
a3.itemsize

8

In [ ]:
#dtype
a1.dtype
a2.dtype
a3.dtype

dtype('int64')